KANBAN-8
xwiki-contrib/macro-kanban pull request #2
Opened 2024-07-12 09:39 UTC by Farcasut

* Added the ability to select colors for all the columns of a Kanban board and removed the ability to click the header and cycle through the default colors since this feature didn't save the new color and everything was reset to the default color when pressing F5. However, if you think that this feature is a must-have and is important for the users, I can add it back.

2024-07-12 12:00 UTC, trrenty requested changes

2024-07-12 12:00 UTC, trrenty commented on src/main/resources/Macros/AWMKanbanMacro.xml
> +#if ($$xcontext.macro.params.colors)
```suggestion
#if ($xcontext.macro.params.colors)
```

2024-07-12 12:00 UTC, trrenty commented on src/main/resources/Macros/AWMKanbanMacro.xml
> +  ## We set as default the original colors: green,blue,orange,yellow,red
Any other macro that uses this one and wants to define some colors can pass them as parameters. You should use an `else` instead of the `elseif`

2024-07-12 12:00 UTC, trrenty commented on src/main/resources/Macros/KanbanMacro.xml
> +                        'yellow':'#FC3',
Duplicate key

2024-07-12 12:00 UTC, trrenty commented on src/main/resources/Macros/KanbanMacro.xml
> +                        color = defaults.colors[board.color] ? defaults.colors[board.color] : board.color;
If `board.color` is defined, wont this line always return `defaults.colors[board.color]`? From what i understand, the `board.color` property has either of `"yellow", "green", "blue", "red", "orange"` values, right? For this code to keep backwards compatibility, the value of the `board.color` needs to be customizable by the user. i.e. by changing the color parameter inside a macro to something other than the predefined values.

2024-07-15 08:14 UTC, Farcasut commented on src/main/resources/Macros/KanbanMacro.xml
> +                        color = defaults.colors[board.color] ? defaults.colors[board.color] : board.color;
The Kanban Macro allows users to choose from only those colors. With this code, I aim to maintain the same shades if the user has utilized that feature. If I simply set the color to 'red' or 'green', the shades will be very different. For any other color, the value will be board.color.

2024-07-15 10:24 UTC, trrenty approved these changes

2024-07-15 11:25 UTC, merged